os: Visual Studio 2017

version: 1.1.0-{branch}-{build}

environment:
    COVERALLS_REPO_TOKEN:
       secure: 9zsHagg7ZmF/Z1MnTaSeFk7xaNeYHuw+OyaULmL+vW5pFllN1UkyjO4Wn/pj759j

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - appveyor-retry dotnet restore
  
test_script:
  - dotnet test "test\Cabinet.Tests\Cabinet.Tests.csproj"

build_script:
  - ps: .\pack.ps1

after_test:
  - cmd: >- 
      "%USERPROFILE%\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe"
      -register:Path32
      -target:"C:\Program Files\dotnet\dotnet.exe" 
      -targetargs:"test -f net46 -c Release test\Cabinet.Tests\Cabinet.Tests.csproj"
      -output:"artifacts\coverage.xml"
      -filter:"+[Cabinet*]* -[Cabinet.Tests*]*"
      -searchdirs:"test\Cabinet.Tests\bin\Release\net46"

  - cmd: >-
      IF DEFINED COVERALLS_REPO_TOKEN "%USERPROFILE%\.nuget\packages\coveralls.io\1.3.4\tools\coveralls.net.exe"
      --opencover
      --repo-token %COVERALLS_REPO_TOKEN%
      --full-sources "artifacts\coverage.xml"

artifacts:
  - path: artifacts\*.*

cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
  
deploy:
  provider: NuGet
  api_key:
    secure: JEFTRpROLptiH7XpQnkTnWo9rWMhiy2i2pfj28CzDgQxO2ad3X7ak7VbmZPrjMDf
  skip_symbols: false
  on:
   appveyor_repo_tag: true
